cooldown-reduction-multiplier: 0.8
kits-config:
  BladeMaster:
    cd: 200
    radius: 3
    damage: 10
  StormKnight:
    cd: 300
    first-arrow-downward-speed: -2
    second-arrow-downward-speed: -3
    third-arrow-downward-speed: -4
  Smasher:
    cd: 800
    explosion-power: 1
  Elf:
    cd: 300
    poison-duration: 40
    poison-amplifier: 0
  Mage:
    cd: 280

