api-version: 1.13
name: KitBattle
main: fun.kaituo.kitbattle.KitBattle
version: 2.0
author: YFshadaow & APairOfMoons & mn_yinduan
depend: [GameUtils,ProtocolLib]
libraries:
  - io.github.classgraph:classgraph:4.8.179
softdepend: [Lobby]
commands:
  kitbattlego:
    description: Choose a kit and spawns the player in the arena
    usage: /kitbattlego <Kit Name>