api-version: 1.13
name: KitBattle
main: fun.kaituo.kitbattle.KitBattle
version: 2.0
author: YFshadaow & APairOfMoons
depend: [GameUtils,ProtocolLib]
softdepend: [Lobby]
commands:
  kitbattlego:
    description: Choose a kit and spawns the player in the arena
    usage: /kitbattlego <Kit Name>