api-version: 1.13
name: KitBattle
main: fun.kaituo.kitbattle.KitBattle
version: 1.2.2
author: YFshadaow & APairOfMoons
depend: [GameUtils,ProtocolLib]
commands:
  kbspawn:
    description: spawn in kitbattle